### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by alagarsamy101189** [engapplabs/flutter_websocket_plugin#13]
2020-10-08 13:46:43.743 W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-10-08 13:46:43.750 W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:239)
2020-10-08 13:46:43.750 W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:350)
2020-10-08 13:46:43.750 W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:308)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:182)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:238)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:111)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:79)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:163)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2020-10-08 13:46:43.751 W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
2020-10-08 13:46:43.752 W/System.err:     at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
2020-10-08 13:46:43.752 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-10-08 13:46:43.752 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-10-08 13:46:43.753 W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-10-08 13:46:43.780 W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-10-08 13:46:43.780 W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:668)
2020-10-08 13:46:43.780 W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:513)
2020-10-08 13:46:43.780 W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:432)
2020-10-08 13:46:43.780 W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:360)
2020-10-08 13:46:43.780 W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2020-10-08 13:46:43.781 W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
2020-10-08 13:46:43.781 W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
2020-10-08 13:46:43.781 W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:430)
2020-10-08 13:46:43.781 W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2020-10-08 13:46:43.781 W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
2020-10-08 13:46:43.781 W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:234)
2020-10-08 13:46:43.781 W/System.err: 	... 23 more
2020-10-08 13:46:43.782 W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by danielwalczak** [comment]
@alagarsamy101189 maybe you should create this issue here -> https://github.com/kunlatek/flutter_websocket_manager_plugin

I also noticed similar issues with android and ios, have to switch to dart web_socket_channel.
it only appears while Im not using wifi.
