### ISSUE TITLE
java.io.EOFException in Android

### ISSUE THREAD

**Issue by ryz418** [engapplabs/flutter_websocket_plugin#19]
I am getting this error when socket is on connection state.

W/System.err(17899): java.io.EOFException
W/System.err(17899): 	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
W/System.err(17899): 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
W/System.err(17899): 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
W/System.err(17899): 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
W/System.err(17899): 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
W/System.err(17899): 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
W/System.err(17899): 	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
W/System.err(17899): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(17899): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(17899): 	at java.lang.Thread.run(Thread.java:919)

please help me with thie error. 
Thanks.

**Comment by maulik-rain** [comment]
same issue
